"""Check current ML and Krita pure behavior against Phase 2 observations.

The observations compared here are generated by the neutral reference policies
and are explicitly marked as current behavior, not canonical expectations.
"""

from __future__ import annotations

import json
import sys

import numpy as np

from .generate import FIXTURE_ROOT, MODEL_PATH, REPOSITORY_ROOT
from .reference import (
    build_canonical_model_tensor,
    canonical_boundary_from_rgba,
    decode_palette_rgba,
    decode_rows_u8,
    score_canonical_regions,
    tensor_from_sparse,
)

sys.path.insert(0, str(REPOSITORY_ROOT / "ml"))
from src.utils.color_utils import (
    get_weighted_most_frequent_color as ml_select_color,
)
from src.utils.flood_fill.core import detect_regions as ml_detect_regions
from src.utils.patch_utils import (
    centered_crop_bounds as ml_centered_crop_bounds,
)
from src.utils.patch_utils import (
    create_region_patches as ml_create_region_patches,
)
from src.utils.patch_utils import (
    region_centroid as ml_region_centroid,
)

sys.path.insert(0, str(REPOSITORY_ROOT / "krita-plugin" / "pykrita"))
from gapfill_krita.engine.detection import detect_gap_regions
from gapfill_krita.engine.patches import (
    build_legacy_model_patches,
    build_model_tensor,
)
from gapfill_krita.engine.patches import (
    canonical_boundary_from_rgba as krita_boundary_from_rgba,
)
from gapfill_krita.engine.postprocessing import (
    segment_colored_regions,
    select_legacy_region_color,
    select_region_prediction,
)
from gapfill_krita.engine.types import GapKind, GapRegion, LayerImages


def _load(relative: str) -> dict:
    return json.loads((FIXTURE_ROOT / relative).read_text(encoding="utf-8"))


def _normalize_component(indices: list[int], width: int, height: int, kind: str) -> dict:
    ordered = sorted(int(value) for value in indices)
    xs = [index % width for index in ordered]
    ys = [index // width for index in ordered]
    return {
        "id": 0,
        "kind": kind,
        "pixel_indices": ordered,
        "pixel_count": len(ordered),
        "centroid": [sum(xs) // len(xs), sum(ys) // len(ys)],
        "bbox": [min(xs), min(ys), max(xs) - min(xs) + 1, max(ys) - min(ys) + 1],
        "touches_image_edge": any(
            x == 0 or y == 0 or x + 1 == width or y + 1 == height
            for x, y in zip(xs, ys)
        ),
        "touches_selection_edge": False,
    }


def _reindex(components: list[dict]) -> list[dict]:
    ordered = sorted(
        components,
        key=lambda component: component["pixel_indices"][0],
    )
    for index, component in enumerate(ordered):
        component["id"] = index
    return ordered


def _ml_detection(case: dict) -> list[dict]:
    line_gray = decode_rows_u8(case["rasters"]["line_gray"])
    labels, count = ml_detect_regions(line_gray, threshold=128)
    components = []
    for label in range(1, int(count) + 1):
        indices = np.flatnonzero(labels.reshape(-1) == label).astype(int).tolist()
        if not indices or len(indices) > int(case["threshold"]):
            continue
        components.append(
            _normalize_component(
                indices, int(case["width"]), int(case["height"]), "transparent"
            )
        )
    return _reindex(components)


def _krita_images(case: dict) -> LayerImages:
    coloring = decode_palette_rgba(case["rasters"]["coloring_rgba"])
    height, width = coloring.shape[:2]
    line = np.zeros((height, width, 4), dtype=np.uint8)
    guide = np.zeros((height, width, 4), dtype=np.uint8)
    line[..., 3] = decode_rows_u8(case["rasters"]["line_alpha"])
    guide[..., 3] = decode_rows_u8(case["rasters"]["guide_alpha"])
    return LayerImages(coloring=coloring, line_art=line, guides=guide)


def _krita_detection(case: dict) -> list[dict]:
    images = _krita_images(case)
    regions = detect_gap_regions(images, int(case["threshold"]))
    components = []
    for region in regions:
        component = _normalize_component(
            region.indices.astype(int).tolist(),
            images.width,
            images.height,
            region.kind.value,
        )
        component["bbox"] = [
            int(region.metadata["bounds"][0]),
            int(region.metadata["bounds"][1]),
            int(region.metadata["bounds"][2]) - int(region.metadata["bounds"][0]),
            int(region.metadata["bounds"][3]) - int(region.metadata["bounds"][1]),
        ]
        components.append(component)
    return _reindex(components)


def check_detection() -> dict:
    cases = {case["id"]: case for case in _load("detection/cases.json")["cases"]}
    rows = _load("parity/characterization.json")["detection"]
    checked = 0
    for row in rows:
        case = cases[row["case_id"]]
        observations = row["observations"]
        actual_ml = _ml_detection(case)
        if actual_ml != observations["ml_python_current"]:
            raise AssertionError(f"{case['id']}: ML detection characterization drifted")
        actual_krita = _krita_detection(case)
        if actual_krita != observations["krita_current"]:
            raise AssertionError(f"{case['id']}: Krita detection characterization drifted")
        checked += 1
    return {"cases": checked, "ml": "MATCH", "krita": "MATCH"}


def _source_arrays(case: dict) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    source = case["source"]
    width, height = int(source["width"]), int(source["height"])
    labels = np.zeros((height, width), dtype=np.int32)
    for index in source["gap_indices"]:
        labels[int(index) // width, int(index) % width] = 1
    line_gray = np.full((height, width), 255, dtype=np.uint8)
    line_alpha = np.zeros((height, width), dtype=np.uint8)
    guide_alpha = np.zeros((height, width), dtype=np.uint8)
    for index in source["line_active_indices"]:
        line_gray[int(index) // width, int(index) % width] = 0
        line_alpha[int(index) // width, int(index) % width] = 255
    for index in source["guide_active_indices"]:
        guide_alpha[int(index) // width, int(index) % width] = 255
    return labels, line_gray, line_alpha, guide_alpha


def _active_indices(mask: np.ndarray) -> list[int]:
    return np.flatnonzero(np.asarray(mask).reshape(-1) > 0).astype(int).tolist()


def check_patch() -> dict:
    data = _load("patch/cases.json")
    checked_ml = 0
    checked_krita = 0
    for case in data["cases"]:
        variants = {item["variant"]: item["result"] for item in case["expectations"]}
        labels, line_gray, line_alpha, guide_alpha = _source_arrays(case)
        source = case["source"]
        width, height = int(source["width"]), int(source["height"])
        center = ml_region_centroid(labels, 1)
        if center is None:
            raise AssertionError(f"{case['id']}: no ML centroid")
        row, column = center
        bounds = ml_centered_crop_bounds(row, column, 32)
        input_patch, _ = ml_create_region_patches(
            line_gray,
            labels,
            1,
            0,
            32,
            128,
            *bounds,
        )
        expected_ml = variants["training_line_only"]
        if [column, row] != expected_ml["centroid"]:
            raise AssertionError(f"{case['id']}: ML centroid drifted")
        if _active_indices(input_patch[..., 0]) != expected_ml["tensor"][
            "channel_0_active_indices"
        ]:
            raise AssertionError(f"{case['id']}: ML channel 0 drifted")
        if _active_indices(input_patch[..., 1]) != expected_ml["tensor"][
            "channel_1_active_indices"
        ]:
            raise AssertionError(f"{case['id']}: ML channel 1 drifted")
        checked_ml += 1

        coloring = np.full((height, width, 4), 255, dtype=np.uint8)
        for index in source["gap_indices"]:
            coloring[int(index) // width, int(index) % width] = (0, 0, 0, 0)
        line = np.zeros_like(coloring)
        guides = np.zeros_like(coloring)
        line[..., 3] = line_alpha
        guides[..., 3] = guide_alpha
        kind = GapKind.GUIDE if case["id"] == "P006_target_guide_suppression" else GapKind.TRANSPARENT
        gap = GapRegion(
            id="gap-0",
            indices=np.asarray(source["gap_indices"], dtype=np.int64),
            center=(column, row),
            kind=kind,
        )
        _, line_patch, guide_patch, gap_mask = build_legacy_model_patches(
            LayerImages(coloring=coloring, line_art=line, guides=guides), gap
        )
        current_variant = (
            "suppress_target_guide"
            if case["id"] == "P006_target_guide_suppression"
            else "line_plus_guide"
            if case["id"] == "P005_guide_delta"
            else "training_line_only"
        )
        expected_krita = variants[current_variant]
        boundary = (line_patch.rgba[..., 3] > 0) | (guide_patch.rgba[..., 3] > 0)
        if _active_indices(boundary) != expected_krita["tensor"][
            "channel_0_active_indices"
        ]:
            raise AssertionError(f"{case['id']}: Krita channel 0 drifted")
        if _active_indices(gap_mask) != expected_krita["tensor"][
            "channel_1_active_indices"
        ]:
            raise AssertionError(f"{case['id']}: Krita channel 1 drifted")
        checked_krita += 1
    return {"cases": len(data["cases"]), "ml": checked_ml, "krita": checked_krita}


def check_model() -> dict:
    import onnxruntime as ort

    data = _load("model/cases.json")
    session = ort.InferenceSession(str(MODEL_PATH), providers=["CPUExecutionProvider"])
    absolute = float(data["comparison_tolerance"]["absolute"])
    relative = float(data["comparison_tolerance"]["relative"])
    maximum_delta = 0.0
    for case in data["cases"]:
        tensor = tensor_from_sparse(case)
        actual = np.asarray(
            session.run(
                [session.get_outputs()[0].name],
                {session.get_inputs()[0].name: tensor},
            )[0],
            dtype=np.float32,
        )
        expected = np.asarray(
            case["characterized_output"]["values_row_major"], dtype=np.float32
        ).reshape(actual.shape)
        maximum_delta = max(
            maximum_delta,
            float(np.max(np.abs(actual.astype(np.float64) - expected.astype(np.float64)))),
        )
        if not np.allclose(actual, expected, atol=absolute, rtol=relative):
            raise AssertionError(f"{case['id']}: ONNX Runtime output drifted")
    return {"cases": len(data["cases"]), "maximum_absolute_delta": maximum_delta}


def check_postprocess() -> dict:
    cases = {case["id"]: case for case in _load("postprocess/cases.json")["cases"]}
    rows = _load("parity/characterization.json")["postprocess"]
    checked = 0
    for row in rows:
        case = cases[row["case_id"]]
        observations = row["observations"]
        rgba = decode_palette_rgba(case["coloring_rgba"])
        probabilities = np.asarray(case["probability_map"], dtype=np.float32)
        label_maps = case["label_maps"]
        first = next(iter(label_maps))
        ml_name = "line_labels" if "line_labels" in label_maps else first
        colored_name = (
            "colored_components"
            if "colored_components" in label_maps
            else "seed_relative"
            if "seed_relative" in label_maps
            else first
        )
        ml_rgb = list(
            ml_select_color(
                rgba[..., :3], np.asarray(label_maps[ml_name], dtype=np.int32), probabilities
            )
        )
        if ml_rgb != observations["ml_python_current"]["rgb"]:
            raise AssertionError(f"{case['id']}: ML postprocess characterization drifted")

        if "seed_relative" in label_maps:
            blank = np.zeros_like(rgba)
            actual_labels, _ = segment_colored_regions(rgba, blank, blank)
            if actual_labels.astype(int).tolist() != label_maps["seed_relative"]:
                raise AssertionError(f"{case['id']}: Krita segmentation drifted")
        labels = np.asarray(label_maps[colored_name], dtype=np.int32)
        krita_rgb = list(
            select_legacy_region_color(
                rgba, labels, int(labels.max(initial=0)), probabilities
            )
        )
        if krita_rgb != observations["krita_current"]["rgb"]:
            raise AssertionError(f"{case['id']}: Krita postprocess characterization drifted")
        checked += 1
    return {"cases": checked, "ml": "MATCH", "krita": "MATCH"}


def check_phase5() -> dict:
    boundary_values = np.asarray(
        [[
            [0, 0, 0, 0],
            [0, 0, 0, 1],
            [127, 127, 127, 255],
            [128, 128, 128, 255],
            [129, 129, 129, 255],
            [0, 0, 0, 255],
            [0, 0, 0, 126],
            [0, 0, 0, 127],
        ]],
        dtype=np.uint8,
    )
    expected_boundary = np.asarray(
        [[False, False, True, True, False, True, False, True]]
    )
    if not np.array_equal(
        canonical_boundary_from_rgba(boundary_values), expected_boundary
    ) or not np.array_equal(
        krita_boundary_from_rgba(boundary_values), expected_boundary
    ):
        raise AssertionError("Phase 5 boundary conversion drifted")

    patch_cases = _load("patch/cases.json")["cases"]
    for case in patch_cases:
        source = case["source"]
        width, height = int(source["width"]), int(source["height"])
        line = np.zeros((height, width, 4), dtype=np.uint8)
        coloring = np.full((height, width, 4), 255, dtype=np.uint8)
        guides = np.zeros_like(coloring)
        for index in source["line_active_indices"]:
            line[int(index) // width, int(index) % width] = (0, 0, 0, 255)
        for index in source["guide_active_indices"]:
            guides[int(index) // width, int(index) % width] = (0, 0, 0, 255)
        for index in source["gap_indices"]:
            coloring[int(index) // width, int(index) % width] = 0
        canonical = next(
            item["result"]
            for item in case["expectations"]
            if item["variant"] == "training_line_only"
        )
        gap = GapRegion(
            id="gap-0",
            indices=np.asarray(source["gap_indices"], dtype=np.int64),
            center=tuple(canonical["centroid"]),
            kind=GapKind.TRANSPARENT,
        )
        reference_tensor, _ = build_canonical_model_tensor(
            line,
            source["gap_indices"],
            tuple(canonical["centroid"]),
        )
        krita_tensor, _ = build_model_tensor(
            LayerImages(coloring=coloring, line_art=line, guides=guides), gap
        )
        if not np.array_equal(reference_tensor, krita_tensor):
            raise AssertionError(f"{case['id']}: Phase 5 tensor parity drifted")

    postprocess_cases = _load("postprocess/cases.json")["cases"]
    for case in postprocess_cases:
        coloring = decode_palette_rgba(case["coloring_rgba"])
        label_maps = case["label_maps"]
        label_name = (
            "line_labels"
            if "line_labels" in label_maps
            else "reviewed_semantic"
            if "reviewed_semantic" in label_maps
            else "selected_region"
        )
        labels = np.asarray(label_maps[label_name], dtype=np.int32)
        probabilities = np.asarray(case["probability_map"], dtype=np.float32)
        reference = score_canonical_regions(coloring, labels, probabilities)
        krita = select_region_prediction(coloring, labels, probabilities)
        if (
            krita.label != reference["selected_region_id"]
            or list(krita.rgb) != reference["rgb"]
            or not np.isclose(
                krita.mean_probability,
                reference["confidence"],
                atol=0.0,
                rtol=0.0,
            )
        ):
            raise AssertionError(f"{case['id']}: Phase 5 postprocessing drifted")
    return {
        "boundary_cases": boundary_values.shape[1],
        "patch_cases": len(patch_cases),
        "postprocess_cases": len(postprocess_cases),
    }


def characterize_phase5_guides() -> dict:
    """Measure A-G Guide-only tensor deltas without claiming distribution support."""

    import onnxruntime as ort

    data = _load("model/cases.json")
    by_id = {case["id"]: case for case in data["cases"]}
    base = set(by_id["M001_no_guide"]["tensor"]["channel_0_active_indices"])
    target = by_id["M001_no_guide"]["tensor"]["channel_1_active_indices"]
    first_half = set(sorted(base)[: len(base) // 2])
    comparisons = {
        "A_no_guide_vs_B_ordinary_guide": (base, base | {534}),
        "C_target_guide_retained_vs_D_suppressed": (base | {528}, base),
        "E_guide_closure": (base - {404}, base),
        "F_isolated_open_guide": (set(), {534}),
        "G_mixed_line_guide_closure": (first_half, base),
    }
    labels = np.zeros((32, 32), dtype=np.int32)
    labels[:, :16] = 1
    labels[:, 16:] = 2
    coloring = np.zeros((32, 32, 4), dtype=np.uint8)
    coloring[:, :16] = (240, 20, 20, 255)
    coloring[:, 16:] = (20, 20, 240, 255)
    coloring.reshape((-1, 4))[target] = 0
    session = ort.InferenceSession(
        str(MODEL_PATH), providers=["CPUExecutionProvider"]
    )

    def infer(boundary: set[int]) -> np.ndarray:
        tensor = np.zeros((1, 2, 32, 32), dtype=np.float32)
        flat = tensor.reshape((1, 2, -1))
        flat[0, 0, sorted(boundary)] = 1.0
        flat[0, 1, target] = 1.0
        return np.asarray(
            session.run(["nearest_region_mask"], {"input_mask": tensor})[0],
            dtype=np.float32,
        )[0, 0]

    results = {}
    for name, (left_boundary, right_boundary) in comparisons.items():
        left = infer(left_boundary)
        right = infer(right_boundary)
        delta = np.abs(left.astype(np.float64) - right.astype(np.float64))
        left_selection = score_canonical_regions(coloring, labels, left)
        right_selection = score_canonical_regions(coloring, labels, right)
        results[name] = {
            "changed_output_values": int(np.count_nonzero(delta)),
            "maximum_absolute_delta": float(delta.max()),
            "mean_absolute_delta": float(delta.mean()),
            "fixed_left_right_selection": [
                {
                    "region": left_selection["selected_region_id"],
                    "rgb": left_selection["rgb"],
                },
                {
                    "region": right_selection["selected_region_id"],
                    "rgb": right_selection["rgb"],
                },
            ],
        }
    return {
        "interpretation": (
            "sensitivity characterization only; Guide-composed inputs were not "
            "present in training"
        ),
        "comparisons": results,
    }


def main() -> None:
    if sys.argv[1:] == ["--phase5"]:
        result = {
            "schema": "gapfill-phase5-characterization-run-v1",
            "model": check_model(),
            "guide_experiments": characterize_phase5_guides(),
            "prediction": check_phase5(),
        }
        print(json.dumps(result, indent=2, sort_keys=True))
        return
    if sys.argv[1:]:
        raise SystemExit("usage: python -m scripts.gapfill_reference.characterize_python [--phase5]")
    result = {
        "schema": "gapfill-python-characterization-run-v1",
        "detection": check_detection(),
        "patch": check_patch(),
        "model": check_model(),
        "postprocess": check_postprocess(),
    }
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
